import { MenuData } from '../component/SubMenus';

export const componentMenus: MenuData[] = [
  { path: '/components/about', name: '关于 UIW' },
  { path: '/components/theme', name: 'Theme' },

  { divider: true, name: '通用' },
  { path: '/components/button', name: 'Button 按钮' },
  { path: '/components/buttongroup', name: 'ButtonGroup 按钮组' },
  { path: '/components/icon', name: 'Icon 图标' },

  { divider: true, name: 'Layout' },
  { path: '/components/divider', name: 'Divider 分割线' },
  { path: '/components/flex', name: 'Flex 布局' },
  { path: '/components/spacing', name: 'Spacing 间距' },
  { path: '/components/typography', name: 'Typography 排版' },
  { path: '/components/winblank', name: 'WingBlank 两翼留白' },

  { divider: true, name: 'Navigation' },
  { path: '/components/menudropdown', name: 'MenuDropdown 菜单下拉按钮' },
  { path: '/components/segmentedcontrol', name: 'SegmentedControl 分段器' },
  { path: '/components/tabs', name: 'Tabs 选项卡' },

  { divider: true, name: 'Data Entry 信息展示' },
  { path: '/components/avatar', name: 'Avatar 头像' },
  { path: '/components/accordion', name: 'Accordion 可折叠/展开的内容区域' },
  { path: '/components/calendar', name: 'Calendar 日历' },
  { path: '/components/card', name: 'Card 卡片' },
  { path: '/components/cardcollapse', name: 'CardCollapse 可折叠卡片列表' },
  { path: '/components/dragdrawer', name: 'Dragdrawer 拖拽抽屉' },
  { path: '/components/expandablesection', name: 'ExpandableSection 展开缩放组件' },
  { path: '/components/ellipsis', name: 'Ellipsis 超出省略' },
  { path: '/components/grid', name: 'Grid 宫格' },
  { path: '/components/imageViewer', name: 'ImageViewer 图片查看' },
  { path: '/components/list', name: 'List 列表' },
  { path: '/components/quicklist', name: 'QuicList 快速列表' },
  { path: '/components/pagination', name: 'Pagination 分页器' },
  { path: '/components/steps', name: 'Steps 步骤条' },
  { path: '/components/swiper', name: 'Swiper 轮播图' },
  { path: '/components/table', name: 'Table 表格' },
  { path: '/components/timeLine', name: 'Timeline 时间轴' },
  { path: '/components/transitionImage', name: 'TransitionImage 图片过渡' },
  { path: '/components/verificationCode', name: 'VerificationCode  验证码倒计时组件' },

  { divider: true, name: 'Data Display 信息录入' },
  { path: '/components/checkbox', name: 'CheckBox 复选框' },
  { path: '/components/datepicker', name: 'DatePicker 日期选择器 🚧' },
  { path: '/components/form', name: 'Form 表单 🚧' },
  { path: '/components/input', name: 'Input 文本输入' },
  { path: '/components/picker', name: 'Picker 选择器 🚧' },
  { path: '/components/radio', name: 'Radio 单选框' },
  { path: '/components/rating', name: 'Rating 评分' },
  { path: '/components/searchbar', name: 'SearchBar 模糊搜索组件' },
  { path: '/components/search-input-bar', name: 'SearchInputBar 搜索栏' },
  { path: '/components/stepper', name: 'Stepper 步进器' },
  { path: '/components/slider', name: 'Slider 滑块输入条' },
  { path: '/components/switch', name: 'Switch 开关' },
  { path: '/components/tree', name: 'Tree 树形控件 🚧' },
  { path: '/components/treeSelect', name: 'TreeSelect 级联选择器 🚧' },

  { divider: true, name: 'Feedback 反馈' },
  { path: '/components/actionSheet', name: 'ActionSheet 动作面板' },
  { path: '/components/drawer', name: 'Drawer 抽屉' },
  { path: '/components/empty', name: 'Empty 空状态' },
  { path: '/components/loader', name: 'Loader 加载' },
  { path: '/components/masklayer', name: 'MaskLayer 遮罩层' },
  { path: '/components/modal', name: 'Modal 模态框' },
  { path: '/components/progress', name: 'Progress 进度条' },
  { path: '/components/result', name: 'Result 结果页' },
  { path: '/components/speeddial', name: 'SpeedDial 悬浮标记' },
  { path: '/components/swipeaction', name: 'SwipeAction 滑动操作组件' },
  { path: '/components/tile', name: 'Tile 卡片' },
  { path: '/components/toast', name: 'Toast 轻提示' },
  { path: '/components/tooltip', name: 'Tooltip 工具提示' },

  { divider: true, name: 'Guidance Prompt 引导提示' },
  { path: '/components/badge', name: 'Badge 标记' },
  { path: '/components/noticebar', name: 'NoticeBar 通告栏' },

  { divider: true, name: '其它' },
  { href: 'https://github.com/uiwjs/react-native-alipay', name: 'Alipay 支付宝', target: '__blank' },
  {
    href: 'https://github.com/uiwjs/react-native-amap-geolocation',
    name: 'AMapGeolocation 高德地图定位',
    target: '__blank',
  },
];

export const docsMenus: MenuData[] = [
  { path: '/docs/getting-started', name: '快速上手' },
  { path: '/docs/development/components', name: '参与组件开发' },
  { path: '/docs/development/document', name: '参与文档网站编辑开发' },
  { path: '/docs/changelog', name: '更新日志' },
  { divider: true, name: '环境安装' },
  { path: '/docs/environment-setup/ios', name: 'iOS 环境安装' },
  { path: '/docs/environment-setup/android', name: 'Android(Mac) 环境安装' },
  { path: '/docs/environment-setup/android-windows', name: 'Android(Windows) 环境安装' },
  { divider: true, name: '真机运行' },
  { path: '/docs/phone-run/ios-phone', name: 'iOS 真机运行' },
  { path: '/docs/phone-run/android-phone', name: 'Android(Mac) 真机运行' },
  { path: '/docs/phone-run/android-windows-phone', name: 'Android(Windows) 真机运行' },
  { divider: true, name: 'APP 打包' },
  { path: '/docs/unpack/ios', name: 'iOS 打包' },
  { path: '/docs/unpack/android', name: 'Android(Mac) 打包' },
  { divider: true, name: 'React Native Template' },
  { path: '/docs/react-native-template/quickstart', name: '快速开始' },
  { path: '/docs/react-native-template/menu-route', name: '菜单路由管理' },
  { path: '/docs/react-native-template/new-page', name: '新增页面' },
  { path: '/docs/react-native-template/mock-data', name: 'Mock 数据' },
  { path: '/docs/react-native-template/log-management', name: '更新日志' },
  { divider: true, name: '发布应用商店' },
  { path: '/docs/app-store/ios', name: '发布 iOS 应用商店' },
  { path: '/docs/app-store/android', name: '发布 Android 应用商店' },
  { divider: true, name: 'react-native常见问题' },
  { path: '/docs/questions', name: '问题总结' },
  { divider: true, name: '其它' },
  { path: '/docs/awesome-react-native', name: 'Awesome React Native' },
  { href: 'https://github.com/facebook/react', target: '_blank', name: 'React 官方文档' },
  { href: 'https://github.com/facebook/react-native', target: '_blank', name: 'React Native 官方文档' },
  { href: 'https://github.com/uiwjs/react-native-uiw/releases', target: '_blank', name: '更新日志' },
];
